services:
  home-frontend:
    image: home-frontend
    container_name: home-frontend
    expose:
      - "3200"
    networks:
      - apps
  home-backend:
    image: home-backend
    container_name: home-backend
    expose:
      - "7000"
    networks:
      - apps
  home-gateway:
    image: home-gateway
    container_name: home-gateway
    ports:
      - "4200:4200"
    networks:
      - apps
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    ports:
      - "21000:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev

networks:
  apps:
    name: apps
    driver: bridge