server:
  port: 4200
spring:
  application:
    name: home-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:http://localhost:21000/realms/katanec}
        registration:
          keycloak:
            provider: keycloak
            client-id: ${CLIENT_ID:katanec}
            client-secret: ${CLIENT_SECRET:ukYfVkORIGvXj79OHD1jd6723Ma6zQwO}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
