server:
  port: 9000

spring:
  security:
    oauth2:
      client:
        provider:
          keycloack-provider:
            issuer-uri: ${ISSUER_URI:http://localhost:8080/auth/realms/katanec}
            authorization-uri: http://localhost:8080/auth/realms/katanec/protocol/openid-connect/auth
            token-uri: ${TOKEN_URI:http://localhost:8080/auth/realms/katanec/protocol/openid-connect/token}
            jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/auth/realms/katanec/protocol/openid-connect/certs}
        registration:
          keycloak-spring-gateway-client:
            provider: keycloack-provider
            client-id: home
            client-secret: ${KC_CLIENT_SECRET:8qj4EVuRGlNBbzFxhlmabYtyf82fEl7H}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: home-backend
          uri: ${HOME_BACKEND_URI:http://localhost:7000}
          predicates:
            - Path=/api/**
        - id: home-frontend
          uri: ${HOME_FRONTEND_URI:http://localhost:3000}
          predicates:
            - Path=/web/**